/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PButton: typeof import('primevue/button')['default']
    PForm: typeof import('@primevue/forms/form')['default']
    PFormField: typeof import('@primevue/forms/formfield')['default']
    PInputMask: typeof import('primevue/inputmask')['default']
    PInputText: typeof import('primevue/inputtext')['default']
    PTextarea: typeof import('primevue/textarea')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
